networks:
  auth-net:
  platform-net:
    external: true

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - auth-net
      - platform-net
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_PROFILES_ACTIVE: docker
      DOMAIN_ADDRESS: https://fixbill.com

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "5433:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U authuser -d authdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth-net

volumes:
  auth-data: