/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.fix.bill.notification.api;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NotificationRequestedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4078320055897123438L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationRequestedEvent\",\"namespace\":\"org.fix.bill.notification.api\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"channel\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"recipient\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"userId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"templateCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"locale\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"category\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"correlationId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"sourceSystem\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NotificationRequestedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotificationRequestedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotificationRequestedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotificationRequestedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotificationRequestedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotificationRequestedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotificationRequestedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotificationRequestedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotificationRequestedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String type;
  private java.lang.String channel;
  private java.lang.String recipient;
  private java.lang.String userId;
  private java.lang.String templateCode;
  private java.lang.String locale;
  private java.lang.String category;
  private java.lang.String correlationId;
  private java.lang.String sourceSystem;
  private java.util.Map<java.lang.String,java.lang.String> data;
  private java.util.Map<java.lang.String,java.lang.String> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotificationRequestedEvent() {}

  /**
   * All-args constructor.
   * @param type The new value for type
   * @param channel The new value for channel
   * @param recipient The new value for recipient
   * @param userId The new value for userId
   * @param templateCode The new value for templateCode
   * @param locale The new value for locale
   * @param category The new value for category
   * @param correlationId The new value for correlationId
   * @param sourceSystem The new value for sourceSystem
   * @param data The new value for data
   * @param metadata The new value for metadata
   */
  public NotificationRequestedEvent(java.lang.String type, java.lang.String channel, java.lang.String recipient, java.lang.String userId, java.lang.String templateCode, java.lang.String locale, java.lang.String category, java.lang.String correlationId, java.lang.String sourceSystem, java.util.Map<java.lang.String,java.lang.String> data, java.util.Map<java.lang.String,java.lang.String> metadata) {
    this.type = type;
    this.channel = channel;
    this.recipient = recipient;
    this.userId = userId;
    this.templateCode = templateCode;
    this.locale = locale;
    this.category = category;
    this.correlationId = correlationId;
    this.sourceSystem = sourceSystem;
    this.data = data;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return type;
    case 1: return channel;
    case 2: return recipient;
    case 3: return userId;
    case 4: return templateCode;
    case 5: return locale;
    case 6: return category;
    case 7: return correlationId;
    case 8: return sourceSystem;
    case 9: return data;
    case 10: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: type = value$ != null ? value$.toString() : null; break;
    case 1: channel = value$ != null ? value$.toString() : null; break;
    case 2: recipient = value$ != null ? value$.toString() : null; break;
    case 3: userId = value$ != null ? value$.toString() : null; break;
    case 4: templateCode = value$ != null ? value$.toString() : null; break;
    case 5: locale = value$ != null ? value$.toString() : null; break;
    case 6: category = value$ != null ? value$.toString() : null; break;
    case 7: correlationId = value$ != null ? value$.toString() : null; break;
    case 8: sourceSystem = value$ != null ? value$.toString() : null; break;
    case 9: data = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    case 10: metadata = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }



  /**
   * Gets the value of the 'channel' field.
   * @return The value of the 'channel' field.
   */
  public java.lang.String getChannel() {
    return channel;
  }



  /**
   * Gets the value of the 'recipient' field.
   * @return The value of the 'recipient' field.
   */
  public java.lang.String getRecipient() {
    return recipient;
  }



  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.String getUserId() {
    return userId;
  }



  /**
   * Gets the value of the 'templateCode' field.
   * @return The value of the 'templateCode' field.
   */
  public java.lang.String getTemplateCode() {
    return templateCode;
  }



  /**
   * Gets the value of the 'locale' field.
   * @return The value of the 'locale' field.
   */
  public java.lang.String getLocale() {
    return locale;
  }



  /**
   * Gets the value of the 'category' field.
   * @return The value of the 'category' field.
   */
  public java.lang.String getCategory() {
    return category;
  }



  /**
   * Gets the value of the 'correlationId' field.
   * @return The value of the 'correlationId' field.
   */
  public java.lang.String getCorrelationId() {
    return correlationId;
  }



  /**
   * Gets the value of the 'sourceSystem' field.
   * @return The value of the 'sourceSystem' field.
   */
  public java.lang.String getSourceSystem() {
    return sourceSystem;
  }



  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getData() {
    return data;
  }



  /**
   * Gets the value of the 'metadata' field.
   * @return The value of the 'metadata' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
    return metadata;
  }



  /**
   * Creates a new NotificationRequestedEvent RecordBuilder.
   * @return A new NotificationRequestedEvent RecordBuilder
   */
  public static org.fix.bill.notification.api.NotificationRequestedEvent.Builder newBuilder() {
    return new org.fix.bill.notification.api.NotificationRequestedEvent.Builder();
  }

  /**
   * Creates a new NotificationRequestedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotificationRequestedEvent RecordBuilder
   */
  public static org.fix.bill.notification.api.NotificationRequestedEvent.Builder newBuilder(org.fix.bill.notification.api.NotificationRequestedEvent.Builder other) {
    if (other == null) {
      return new org.fix.bill.notification.api.NotificationRequestedEvent.Builder();
    } else {
      return new org.fix.bill.notification.api.NotificationRequestedEvent.Builder(other);
    }
  }

  /**
   * Creates a new NotificationRequestedEvent RecordBuilder by copying an existing NotificationRequestedEvent instance.
   * @param other The existing instance to copy.
   * @return A new NotificationRequestedEvent RecordBuilder
   */
  public static org.fix.bill.notification.api.NotificationRequestedEvent.Builder newBuilder(org.fix.bill.notification.api.NotificationRequestedEvent other) {
    if (other == null) {
      return new org.fix.bill.notification.api.NotificationRequestedEvent.Builder();
    } else {
      return new org.fix.bill.notification.api.NotificationRequestedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotificationRequestedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationRequestedEvent>
    implements org.apache.avro.data.RecordBuilder<NotificationRequestedEvent> {

    private java.lang.String type;
    private java.lang.String channel;
    private java.lang.String recipient;
    private java.lang.String userId;
    private java.lang.String templateCode;
    private java.lang.String locale;
    private java.lang.String category;
    private java.lang.String correlationId;
    private java.lang.String sourceSystem;
    private java.util.Map<java.lang.String,java.lang.String> data;
    private java.util.Map<java.lang.String,java.lang.String> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.fix.bill.notification.api.NotificationRequestedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.channel)) {
        this.channel = data().deepCopy(fields()[1].schema(), other.channel);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.recipient)) {
        this.recipient = data().deepCopy(fields()[2].schema(), other.recipient);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.templateCode)) {
        this.templateCode = data().deepCopy(fields()[4].schema(), other.templateCode);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.locale)) {
        this.locale = data().deepCopy(fields()[5].schema(), other.locale);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.category)) {
        this.category = data().deepCopy(fields()[6].schema(), other.category);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[7].schema(), other.correlationId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.sourceSystem)) {
        this.sourceSystem = data().deepCopy(fields()[8].schema(), other.sourceSystem);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.data)) {
        this.data = data().deepCopy(fields()[9].schema(), other.data);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.metadata)) {
        this.metadata = data().deepCopy(fields()[10].schema(), other.metadata);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
    }

    /**
     * Creates a Builder by copying an existing NotificationRequestedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(org.fix.bill.notification.api.NotificationRequestedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.type)) {
        this.type = data().deepCopy(fields()[0].schema(), other.type);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.channel)) {
        this.channel = data().deepCopy(fields()[1].schema(), other.channel);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.recipient)) {
        this.recipient = data().deepCopy(fields()[2].schema(), other.recipient);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.templateCode)) {
        this.templateCode = data().deepCopy(fields()[4].schema(), other.templateCode);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locale)) {
        this.locale = data().deepCopy(fields()[5].schema(), other.locale);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.category)) {
        this.category = data().deepCopy(fields()[6].schema(), other.category);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.correlationId)) {
        this.correlationId = data().deepCopy(fields()[7].schema(), other.correlationId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.sourceSystem)) {
        this.sourceSystem = data().deepCopy(fields()[8].schema(), other.sourceSystem);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.data)) {
        this.data = data().deepCopy(fields()[9].schema(), other.data);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.metadata)) {
        this.metadata = data().deepCopy(fields()[10].schema(), other.metadata);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setType(java.lang.String value) {
      validate(fields()[0], value);
      this.type = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearType() {
      type = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'channel' field.
      * @return The value.
      */
    public java.lang.String getChannel() {
      return channel;
    }


    /**
      * Sets the value of the 'channel' field.
      * @param value The value of 'channel'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setChannel(java.lang.String value) {
      validate(fields()[1], value);
      this.channel = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'channel' field has been set.
      * @return True if the 'channel' field has been set, false otherwise.
      */
    public boolean hasChannel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'channel' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearChannel() {
      channel = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'recipient' field.
      * @return The value.
      */
    public java.lang.String getRecipient() {
      return recipient;
    }


    /**
      * Sets the value of the 'recipient' field.
      * @param value The value of 'recipient'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setRecipient(java.lang.String value) {
      validate(fields()[2], value);
      this.recipient = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'recipient' field has been set.
      * @return True if the 'recipient' field has been set, false otherwise.
      */
    public boolean hasRecipient() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'recipient' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearRecipient() {
      recipient = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.String getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setUserId(java.lang.String value) {
      validate(fields()[3], value);
      this.userId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'templateCode' field.
      * @return The value.
      */
    public java.lang.String getTemplateCode() {
      return templateCode;
    }


    /**
      * Sets the value of the 'templateCode' field.
      * @param value The value of 'templateCode'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setTemplateCode(java.lang.String value) {
      validate(fields()[4], value);
      this.templateCode = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'templateCode' field has been set.
      * @return True if the 'templateCode' field has been set, false otherwise.
      */
    public boolean hasTemplateCode() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'templateCode' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearTemplateCode() {
      templateCode = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'locale' field.
      * @return The value.
      */
    public java.lang.String getLocale() {
      return locale;
    }


    /**
      * Sets the value of the 'locale' field.
      * @param value The value of 'locale'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setLocale(java.lang.String value) {
      validate(fields()[5], value);
      this.locale = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'locale' field has been set.
      * @return True if the 'locale' field has been set, false otherwise.
      */
    public boolean hasLocale() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'locale' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearLocale() {
      locale = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'category' field.
      * @return The value.
      */
    public java.lang.String getCategory() {
      return category;
    }


    /**
      * Sets the value of the 'category' field.
      * @param value The value of 'category'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setCategory(java.lang.String value) {
      validate(fields()[6], value);
      this.category = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'category' field has been set.
      * @return True if the 'category' field has been set, false otherwise.
      */
    public boolean hasCategory() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'category' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearCategory() {
      category = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'correlationId' field.
      * @return The value.
      */
    public java.lang.String getCorrelationId() {
      return correlationId;
    }


    /**
      * Sets the value of the 'correlationId' field.
      * @param value The value of 'correlationId'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setCorrelationId(java.lang.String value) {
      validate(fields()[7], value);
      this.correlationId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'correlationId' field has been set.
      * @return True if the 'correlationId' field has been set, false otherwise.
      */
    public boolean hasCorrelationId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'correlationId' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearCorrelationId() {
      correlationId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'sourceSystem' field.
      * @return The value.
      */
    public java.lang.String getSourceSystem() {
      return sourceSystem;
    }


    /**
      * Sets the value of the 'sourceSystem' field.
      * @param value The value of 'sourceSystem'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setSourceSystem(java.lang.String value) {
      validate(fields()[8], value);
      this.sourceSystem = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceSystem' field has been set.
      * @return True if the 'sourceSystem' field has been set, false otherwise.
      */
    public boolean hasSourceSystem() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'sourceSystem' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearSourceSystem() {
      sourceSystem = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getData() {
      return data;
    }


    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setData(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[9], value);
      this.data = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearData() {
      data = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[10], value);
      this.metadata = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'metadata' field.
      * @return This builder.
      */
    public org.fix.bill.notification.api.NotificationRequestedEvent.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotificationRequestedEvent build() {
      try {
        NotificationRequestedEvent record = new NotificationRequestedEvent();
        record.type = fieldSetFlags()[0] ? this.type : (java.lang.String) defaultValue(fields()[0]);
        record.channel = fieldSetFlags()[1] ? this.channel : (java.lang.String) defaultValue(fields()[1]);
        record.recipient = fieldSetFlags()[2] ? this.recipient : (java.lang.String) defaultValue(fields()[2]);
        record.userId = fieldSetFlags()[3] ? this.userId : (java.lang.String) defaultValue(fields()[3]);
        record.templateCode = fieldSetFlags()[4] ? this.templateCode : (java.lang.String) defaultValue(fields()[4]);
        record.locale = fieldSetFlags()[5] ? this.locale : (java.lang.String) defaultValue(fields()[5]);
        record.category = fieldSetFlags()[6] ? this.category : (java.lang.String) defaultValue(fields()[6]);
        record.correlationId = fieldSetFlags()[7] ? this.correlationId : (java.lang.String) defaultValue(fields()[7]);
        record.sourceSystem = fieldSetFlags()[8] ? this.sourceSystem : (java.lang.String) defaultValue(fields()[8]);
        record.data = fieldSetFlags()[9] ? this.data : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[9]);
        record.metadata = fieldSetFlags()[10] ? this.metadata : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[10]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotificationRequestedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotificationRequestedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotificationRequestedEvent>
    READER$ = (org.apache.avro.io.DatumReader<NotificationRequestedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.type);

    out.writeString(this.channel);

    out.writeString(this.recipient);

    if (this.userId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.userId);
    }

    out.writeString(this.templateCode);

    if (this.locale == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.locale);
    }

    if (this.category == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.category);
    }

    if (this.correlationId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.correlationId);
    }

    if (this.sourceSystem == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.sourceSystem);
    }

    long size0 = this.data.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> e0: this.data.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.String v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    if (this.metadata == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size1 = this.metadata.size();
      out.writeMapStart();
      out.setItemCount(size1);
      long actualSize1 = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> e1: this.metadata.entrySet()) {
        actualSize1++;
        out.startItem();
        out.writeString(e1.getKey());
        java.lang.String v1 = e1.getValue();
        out.writeString(v1);
      }
      out.writeMapEnd();
      if (actualSize1 != size1)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size1 + ", but element count was " + actualSize1 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.type = in.readString();

      this.channel = in.readString();

      this.recipient = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.userId = null;
      } else {
        this.userId = in.readString();
      }

      this.templateCode = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.locale = null;
      } else {
        this.locale = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.category = null;
      } else {
        this.category = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.correlationId = null;
      } else {
        this.correlationId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.sourceSystem = null;
      } else {
        this.sourceSystem = in.readString();
      }

      long size0 = in.readMapStart();
      java.util.Map<java.lang.String,java.lang.String> m0 = this.data; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size0 * 4)/3 + 1);
        this.data = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String k0 = null;
          k0 = in.readString();
          java.lang.String v0 = null;
          v0 = in.readString();
          m0.put(k0, v0);
        }
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.metadata = null;
      } else {
        long size1 = in.readMapStart();
        java.util.Map<java.lang.String,java.lang.String> m1 = this.metadata; // Need fresh name due to limitation of macro system
        if (m1 == null) {
          m1 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size1 * 4)/3 + 1);
          this.metadata = m1;
        } else m1.clear();
        for ( ; 0 < size1; size1 = in.mapNext()) {
          for ( ; size1 != 0; size1--) {
            java.lang.String k1 = null;
            k1 = in.readString();
            java.lang.String v1 = null;
            v1 = in.readString();
            m1.put(k1, v1);
          }
        }
      }

    } else {
      for (int i = 0; i < 11; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.type = in.readString();
          break;

        case 1:
          this.channel = in.readString();
          break;

        case 2:
          this.recipient = in.readString();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.userId = null;
          } else {
            this.userId = in.readString();
          }
          break;

        case 4:
          this.templateCode = in.readString();
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.locale = null;
          } else {
            this.locale = in.readString();
          }
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.category = null;
          } else {
            this.category = in.readString();
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.correlationId = null;
          } else {
            this.correlationId = in.readString();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sourceSystem = null;
          } else {
            this.sourceSystem = in.readString();
          }
          break;

        case 9:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.String,java.lang.String> m0 = this.data; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size0 * 4)/3 + 1);
            this.data = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String k0 = null;
              k0 = in.readString();
              java.lang.String v0 = null;
              v0 = in.readString();
              m0.put(k0, v0);
            }
          }
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.metadata = null;
          } else {
            long size1 = in.readMapStart();
            java.util.Map<java.lang.String,java.lang.String> m1 = this.metadata; // Need fresh name due to limitation of macro system
            if (m1 == null) {
              m1 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size1 * 4)/3 + 1);
              this.metadata = m1;
            } else m1.clear();
            for ( ; 0 < size1; size1 = in.mapNext()) {
              for ( ; size1 != 0; size1--) {
                java.lang.String k1 = null;
                k1 = in.readString();
                java.lang.String v1 = null;
                v1 = in.readString();
                m1.put(k1, v1);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










