{
  "type": "record",
  "name": "NotificationRequestedEvent",
  "namespace": "org.fix.bill.notification.api",
  "fields": [
    {
      "name": "type",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "channel",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "recipient",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "userId",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },
    {
      "name": "templateCode",
      "type": {
        "type": "string",
        "avro.java.string": "String"
      }
    },
    {
      "name": "locale",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },
    {
      "name": "category",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },
    {
      "name": "correlationId",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },
    {
      "name": "sourceSystem",
      "type": [
        "null",
        {
          "type": "string",
          "avro.java.string": "String"
        }
      ],
      "default": null
    },
    {
      "name": "data",
      "type": {
        "type": "map",
        "values": {
          "type": "string",
          "avro.java.string": "String"
        }
      }
    },
    {
      "name": "metadata",
      "type": [
        "null",
        {
          "type": "map",
          "values": {
            "type": "string",
            "avro.java.string": "String"
          }
        }
      ],
      "default": null
    }
  ]
}
