dependencies {

    implementation libs.bouncy.castle
    implementation libs.jjwt.api
    implementation libs.avro
    runtimeOnly libs.jjwt.impl
    runtimeOnly libs.jjwt.jackson

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.kafka:spring-kafka'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.postgresql:postgresql'

    implementation libs.apache.http.client

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}