spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/authdb
    username: authuser
    password: authpass

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema:
        registry:
          url: http://localhost:8081
